#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libopenzwave
Version  : 0.4.11
Release  : 4
URL      : https://raw.githubusercontent.com/OpenZWave/python-openzwave/master/archives/open-zwave-master-0.4.11.zip
Source0  : https://raw.githubusercontent.com/OpenZWave/python-openzwave/master/archives/open-zwave-master-0.4.11.zip
Summary  : Library to access Z-Wave interfaces
Group    : Development/Tools
License  : BSD-3-Clause GPL-3.0 ISC LGPL-2.0+ LGPL-2.1+ LGPL-3.0
Requires: libopenzwave-bin = %{version}-%{release}
Requires: libopenzwave-data = %{version}-%{release}
Requires: libopenzwave-lib = %{version}-%{release}
Requires: libopenzwave-license = %{version}-%{release}
BuildRequires : docbook-xml
BuildRequires : doxygen
BuildRequires : graphviz
BuildRequires : libxml2-dev
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libusb-1.0)
Patch1: nowerror.patch
Patch2: nodocs.patch

%description
OpenZWave is an open-source, cross-platform library designed to enable anyone to
add support for Z-Wave home-automation devices to their applications, without 
requiring any in depth knowledge of the Z-Wave protocol.

Z-Wave employs a proprietary protocol which the owners, Sigma Designs, have 
chosen not to release into the public domain. There is also no official free 
or low-cost SDK that can be used to develop applications (The ControlThink SDK
is now tied exclusively to their own Z-Wave PC interface). The only way to 
obtain the protocol documentation and sample code is to purchase an expensive 
development kit, and sign a non-disclosure agreement (NDA) preventing the 
release of that knowledge.

OpenZWave was created to fill that gap. We do not have the official 
documentation, have signed no NDA, and are free to develop the library as we 
see fit. Our knowledge comes from existing bodies of open-source code 
(principally the Z-Wave parts of LinuxMCE), and through examining the 
messages sent by Z-Wave devices.

The goal of the project is to make a positive contribution to the Z-Wave 
community by creating a library that supports as much of the Z-Wave 
specification as possible, and that can be used as a "black-box" solution 
by anyone wanting to add Z-Wave to their application. It is NOT our aim 
to publish alternative documentation of the Z-Wave protocol, or to 
attempt to "punish" Sigma Designs for their decision to keep the 
protocol closed.

%package bin
Summary: bin components for the libopenzwave package.
Group: Binaries
Requires: libopenzwave-data = %{version}-%{release}
Requires: libopenzwave-license = %{version}-%{release}

%description bin
bin components for the libopenzwave package.


%package data
Summary: data components for the libopenzwave package.
Group: Data

%description data
data components for the libopenzwave package.


%package dev
Summary: dev components for the libopenzwave package.
Group: Development
Requires: libopenzwave-lib = %{version}-%{release}
Requires: libopenzwave-bin = %{version}-%{release}
Requires: libopenzwave-data = %{version}-%{release}
Provides: libopenzwave-devel = %{version}-%{release}

%description dev
dev components for the libopenzwave package.


%package doc
Summary: doc components for the libopenzwave package.
Group: Documentation

%description doc
doc components for the libopenzwave package.


%package lib
Summary: lib components for the libopenzwave package.
Group: Libraries
Requires: libopenzwave-data = %{version}-%{release}
Requires: libopenzwave-license = %{version}-%{release}

%description lib
lib components for the libopenzwave package.


%package license
Summary: license components for the libopenzwave package.
Group: Default

%description license
license components for the libopenzwave package.


%prep
%setup -q -n open-zwave-master
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1541745599
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1541745599
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libopenzwave
cp cpp/hidapi/LICENSE-bsd.txt %{buildroot}/usr/share/package-licenses/libopenzwave/cpp_hidapi_LICENSE-bsd.txt
cp cpp/hidapi/LICENSE-gpl3.txt %{buildroot}/usr/share/package-licenses/libopenzwave/cpp_hidapi_LICENSE-gpl3.txt
cp cpp/hidapi/LICENSE-orig.txt %{buildroot}/usr/share/package-licenses/libopenzwave/cpp_hidapi_LICENSE-orig.txt
cp cpp/hidapi/LICENSE.txt %{buildroot}/usr/share/package-licenses/libopenzwave/cpp_hidapi_LICENSE.txt
cp debian/copyright %{buildroot}/usr/share/package-licenses/libopenzwave/debian_copyright
cp license/gpl.txt %{buildroot}/usr/share/package-licenses/libopenzwave/license_gpl.txt
cp license/license.txt %{buildroot}/usr/share/package-licenses/libopenzwave/license_license.txt
%make_install PREFIX=/usr sysconfdir=/usr/share/defaults/openzwave

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/MinOZW
/usr/bin/ozw_config

%files data
%defattr(-,root,root,-)
/usr/share/defaults/openzwave/2gig/ct100.xml
/usr/share/defaults/openzwave/2gig/ct101.xml
/usr/share/defaults/openzwave/2gig/ct30.xml
/usr/share/defaults/openzwave/2gig/ct32.xml
/usr/share/defaults/openzwave/2gig/ct50e.xml
/usr/share/defaults/openzwave/2gig/ct80.xml
/usr/share/defaults/openzwave/BeNext/1poleswitch.xml
/usr/share/defaults/openzwave/BeNext/2poleswitch.xml
/usr/share/defaults/openzwave/BeNext/AlarmSound.xml
/usr/share/defaults/openzwave/BeNext/BuiltinDimmer.xml
/usr/share/defaults/openzwave/BeNext/DoorSensor.xml
/usr/share/defaults/openzwave/BeNext/EnergySwitch.xml
/usr/share/defaults/openzwave/BeNext/HeatingControl.xml
/usr/share/defaults/openzwave/BeNext/Molite.xml
/usr/share/defaults/openzwave/BeNext/P1dongle.xml
/usr/share/defaults/openzwave/BeNext/PanicButton.xml
/usr/share/defaults/openzwave/BeNext/PanicWatch.xml
/usr/share/defaults/openzwave/BeNext/PluginDimmer.xml
/usr/share/defaults/openzwave/BeNext/SceneController.xml
/usr/share/defaults/openzwave/BeNext/TagReader.xml
/usr/share/defaults/openzwave/BeNext/TagReader500.xml
/usr/share/defaults/openzwave/act/lfm20.xml
/usr/share/defaults/openzwave/act/zdm230.xml
/usr/share/defaults/openzwave/act/zdw103.xml
/usr/share/defaults/openzwave/act/zdw232.xml
/usr/share/defaults/openzwave/act/zir010.xml
/usr/share/defaults/openzwave/act/zrp110.xml
/usr/share/defaults/openzwave/act/zrw103.xml
/usr/share/defaults/openzwave/aeotec/dsa03202.xml
/usr/share/defaults/openzwave/aeotec/dsa22.xml
/usr/share/defaults/openzwave/aeotec/dsa38.xml
/usr/share/defaults/openzwave/aeotec/dsb04100.xml
/usr/share/defaults/openzwave/aeotec/dsb05.xml
/usr/share/defaults/openzwave/aeotec/dsb09104.xml
/usr/share/defaults/openzwave/aeotec/dsb28.xml
/usr/share/defaults/openzwave/aeotec/dsb29.xml
/usr/share/defaults/openzwave/aeotec/dsb45.xml
/usr/share/defaults/openzwave/aeotec/dsb54.xml
/usr/share/defaults/openzwave/aeotec/dsc06106.xml
/usr/share/defaults/openzwave/aeotec/dsc08101.xml
/usr/share/defaults/openzwave/aeotec/dsc10.xml
/usr/share/defaults/openzwave/aeotec/dsc11.xml
/usr/share/defaults/openzwave/aeotec/dsc12104.xml
/usr/share/defaults/openzwave/aeotec/dsc13104.xml
/usr/share/defaults/openzwave/aeotec/dsc14104.xml
/usr/share/defaults/openzwave/aeotec/dsc18103.xml
/usr/share/defaults/openzwave/aeotec/dsc19103.xml
/usr/share/defaults/openzwave/aeotec/dsc24.xml
/usr/share/defaults/openzwave/aeotec/dsc26103.xml
/usr/share/defaults/openzwave/aeotec/dsc27103.xml
/usr/share/defaults/openzwave/aeotec/dsc35103.xml
/usr/share/defaults/openzwave/aeotec/dsd37.xml
/usr/share/defaults/openzwave/aeotec/zw056.xml
/usr/share/defaults/openzwave/aeotec/zw062.xml
/usr/share/defaults/openzwave/aeotec/zw074.xml
/usr/share/defaults/openzwave/aeotec/zw075.xml
/usr/share/defaults/openzwave/aeotec/zw078.xml
/usr/share/defaults/openzwave/aeotec/zw080.xml
/usr/share/defaults/openzwave/aeotec/zw088.xml
/usr/share/defaults/openzwave/aeotec/zw089.xml
/usr/share/defaults/openzwave/aeotec/zw090.xml
/usr/share/defaults/openzwave/aeotec/zw095.xml
/usr/share/defaults/openzwave/aeotec/zw096.xml
/usr/share/defaults/openzwave/aeotec/zw097.xml
/usr/share/defaults/openzwave/aeotec/zw098.xml
/usr/share/defaults/openzwave/aeotec/zw099.xml
/usr/share/defaults/openzwave/aeotec/zw100.xml
/usr/share/defaults/openzwave/aeotec/zw111.xml
/usr/share/defaults/openzwave/aeotec/zw112.xml
/usr/share/defaults/openzwave/aeotec/zw116.xml
/usr/share/defaults/openzwave/aeotec/zw117.xml
/usr/share/defaults/openzwave/aeotec/zw120.xml
/usr/share/defaults/openzwave/aeotec/zw121.xml
/usr/share/defaults/openzwave/aeotec/zw122.xml
/usr/share/defaults/openzwave/aeotec/zw129.xml
/usr/share/defaults/openzwave/aeotec/zw130.xml
/usr/share/defaults/openzwave/aeotec/zw132.xml
/usr/share/defaults/openzwave/aeotec/zw139.xml
/usr/share/defaults/openzwave/aeotec/zw140.xml
/usr/share/defaults/openzwave/aeotec/zw141.xml
/usr/share/defaults/openzwave/aeotec/zwa001.xml
/usr/share/defaults/openzwave/aeotec/zwa002.xml
/usr/share/defaults/openzwave/aeotec/zwa003.xml
/usr/share/defaults/openzwave/aeotec/zwa004.xml
/usr/share/defaults/openzwave/aeotec/zwa005.xml
/usr/share/defaults/openzwave/assa_abloy/ConexisL1.xml
/usr/share/defaults/openzwave/assa_abloy/KeyfreeConnected-plus.xml
/usr/share/defaults/openzwave/assa_abloy/KeyfreeConnected.xml
/usr/share/defaults/openzwave/assa_abloy/PushButtonDeadbolt.xml
/usr/share/defaults/openzwave/assa_abloy/PushButtonLever.xml
/usr/share/defaults/openzwave/assa_abloy/TouchDeadbolt.xml
/usr/share/defaults/openzwave/assa_abloy/TouchLever.xml
/usr/share/defaults/openzwave/assa_abloy/nexTouch.xml
/usr/share/defaults/openzwave/august/asl-03.xml
/usr/share/defaults/openzwave/config/2gig/ct100.xml
/usr/share/defaults/openzwave/config/2gig/ct101.xml
/usr/share/defaults/openzwave/config/2gig/ct30.xml
/usr/share/defaults/openzwave/config/2gig/ct32.xml
/usr/share/defaults/openzwave/config/2gig/ct50e.xml
/usr/share/defaults/openzwave/config/2gig/ct80.xml
/usr/share/defaults/openzwave/config/BeNext/1poleswitch.xml
/usr/share/defaults/openzwave/config/BeNext/2poleswitch.xml
/usr/share/defaults/openzwave/config/BeNext/AlarmSound.xml
/usr/share/defaults/openzwave/config/BeNext/BuiltinDimmer.xml
/usr/share/defaults/openzwave/config/BeNext/DoorSensor.xml
/usr/share/defaults/openzwave/config/BeNext/EnergySwitch.xml
/usr/share/defaults/openzwave/config/BeNext/HeatingControl.xml
/usr/share/defaults/openzwave/config/BeNext/Molite.xml
/usr/share/defaults/openzwave/config/BeNext/P1dongle.xml
/usr/share/defaults/openzwave/config/BeNext/PanicButton.xml
/usr/share/defaults/openzwave/config/BeNext/PanicWatch.xml
/usr/share/defaults/openzwave/config/BeNext/PluginDimmer.xml
/usr/share/defaults/openzwave/config/BeNext/SceneController.xml
/usr/share/defaults/openzwave/config/BeNext/TagReader.xml
/usr/share/defaults/openzwave/config/BeNext/TagReader500.xml
/usr/share/defaults/openzwave/config/act/lfm20.xml
/usr/share/defaults/openzwave/config/act/zdm230.xml
/usr/share/defaults/openzwave/config/act/zdw103.xml
/usr/share/defaults/openzwave/config/act/zdw232.xml
/usr/share/defaults/openzwave/config/act/zir010.xml
/usr/share/defaults/openzwave/config/act/zrp110.xml
/usr/share/defaults/openzwave/config/act/zrw103.xml
/usr/share/defaults/openzwave/config/aeotec/dsa03202.xml
/usr/share/defaults/openzwave/config/aeotec/dsa22.xml
/usr/share/defaults/openzwave/config/aeotec/dsa38.xml
/usr/share/defaults/openzwave/config/aeotec/dsb04100.xml
/usr/share/defaults/openzwave/config/aeotec/dsb05.xml
/usr/share/defaults/openzwave/config/aeotec/dsb09104.xml
/usr/share/defaults/openzwave/config/aeotec/dsb28.xml
/usr/share/defaults/openzwave/config/aeotec/dsb29.xml
/usr/share/defaults/openzwave/config/aeotec/dsb45.xml
/usr/share/defaults/openzwave/config/aeotec/dsb54.xml
/usr/share/defaults/openzwave/config/aeotec/dsc06106.xml
/usr/share/defaults/openzwave/config/aeotec/dsc08101.xml
/usr/share/defaults/openzwave/config/aeotec/dsc10.xml
/usr/share/defaults/openzwave/config/aeotec/dsc11.xml
/usr/share/defaults/openzwave/config/aeotec/dsc12104.xml
/usr/share/defaults/openzwave/config/aeotec/dsc13104.xml
/usr/share/defaults/openzwave/config/aeotec/dsc14104.xml
/usr/share/defaults/openzwave/config/aeotec/dsc18103.xml
/usr/share/defaults/openzwave/config/aeotec/dsc19103.xml
/usr/share/defaults/openzwave/config/aeotec/dsc24.xml
/usr/share/defaults/openzwave/config/aeotec/dsc26103.xml
/usr/share/defaults/openzwave/config/aeotec/dsc27103.xml
/usr/share/defaults/openzwave/config/aeotec/dsc35103.xml
/usr/share/defaults/openzwave/config/aeotec/dsd37.xml
/usr/share/defaults/openzwave/config/aeotec/zw056.xml
/usr/share/defaults/openzwave/config/aeotec/zw062.xml
/usr/share/defaults/openzwave/config/aeotec/zw074.xml
/usr/share/defaults/openzwave/config/aeotec/zw075.xml
/usr/share/defaults/openzwave/config/aeotec/zw078.xml
/usr/share/defaults/openzwave/config/aeotec/zw080.xml
/usr/share/defaults/openzwave/config/aeotec/zw088.xml
/usr/share/defaults/openzwave/config/aeotec/zw089.xml
/usr/share/defaults/openzwave/config/aeotec/zw090.xml
/usr/share/defaults/openzwave/config/aeotec/zw095.xml
/usr/share/defaults/openzwave/config/aeotec/zw096.xml
/usr/share/defaults/openzwave/config/aeotec/zw097.xml
/usr/share/defaults/openzwave/config/aeotec/zw098.xml
/usr/share/defaults/openzwave/config/aeotec/zw099.xml
/usr/share/defaults/openzwave/config/aeotec/zw100.xml
/usr/share/defaults/openzwave/config/aeotec/zw111.xml
/usr/share/defaults/openzwave/config/aeotec/zw112.xml
/usr/share/defaults/openzwave/config/aeotec/zw116.xml
/usr/share/defaults/openzwave/config/aeotec/zw117.xml
/usr/share/defaults/openzwave/config/aeotec/zw120.xml
/usr/share/defaults/openzwave/config/aeotec/zw121.xml
/usr/share/defaults/openzwave/config/aeotec/zw122.xml
/usr/share/defaults/openzwave/config/aeotec/zw129.xml
/usr/share/defaults/openzwave/config/aeotec/zw130.xml
/usr/share/defaults/openzwave/config/aeotec/zw132.xml
/usr/share/defaults/openzwave/config/aeotec/zw139.xml
/usr/share/defaults/openzwave/config/aeotec/zw140.xml
/usr/share/defaults/openzwave/config/aeotec/zw141.xml
/usr/share/defaults/openzwave/config/aeotec/zwa001.xml
/usr/share/defaults/openzwave/config/aeotec/zwa002.xml
/usr/share/defaults/openzwave/config/aeotec/zwa003.xml
/usr/share/defaults/openzwave/config/aeotec/zwa004.xml
/usr/share/defaults/openzwave/config/aeotec/zwa005.xml
/usr/share/defaults/openzwave/config/assa_abloy/ConexisL1.xml
/usr/share/defaults/openzwave/config/assa_abloy/KeyfreeConnected-plus.xml
/usr/share/defaults/openzwave/config/assa_abloy/KeyfreeConnected.xml
/usr/share/defaults/openzwave/config/assa_abloy/PushButtonDeadbolt.xml
/usr/share/defaults/openzwave/config/assa_abloy/PushButtonLever.xml
/usr/share/defaults/openzwave/config/assa_abloy/TouchDeadbolt.xml
/usr/share/defaults/openzwave/config/assa_abloy/TouchLever.xml
/usr/share/defaults/openzwave/config/assa_abloy/nexTouch.xml
/usr/share/defaults/openzwave/config/august/asl-03.xml
/usr/share/defaults/openzwave/config/cooper/RF9501.xml
/usr/share/defaults/openzwave/config/cooper/RF9505-T.xml
/usr/share/defaults/openzwave/config/cooper/RF9517.xml
/usr/share/defaults/openzwave/config/cooper/RF9540-N.xml
/usr/share/defaults/openzwave/config/cooper/RF9542-Z.xml
/usr/share/defaults/openzwave/config/cooper/RFWC5.xml
/usr/share/defaults/openzwave/config/danfoss/living.xml
/usr/share/defaults/openzwave/config/danfoss/rsroom.xml
/usr/share/defaults/openzwave/config/danfoss/z.xml
/usr/share/defaults/openzwave/config/device_classes.xml
/usr/share/defaults/openzwave/config/device_classes.xsd
/usr/share/defaults/openzwave/config/device_configuration.xsd
/usr/share/defaults/openzwave/config/devolo/connectz.xml
/usr/share/defaults/openzwave/config/devolo/mt02648.xml
/usr/share/defaults/openzwave/config/devolo/mt02755.xml
/usr/share/defaults/openzwave/config/devolo/mt02758.xml
/usr/share/defaults/openzwave/config/devolo/mt02792.xml
/usr/share/defaults/openzwave/config/devolo/mt2646.xml
/usr/share/defaults/openzwave/config/devolo/mt2647.xml
/usr/share/defaults/openzwave/config/devolo/mt2651.xml
/usr/share/defaults/openzwave/config/devolo/mt2652.xml
/usr/share/defaults/openzwave/config/devolo/mt2653.xml
/usr/share/defaults/openzwave/config/devolo/mt2756.xml
/usr/share/defaults/openzwave/config/devolo/rs014G0159.xml
/usr/share/defaults/openzwave/config/dlink/dch-z110.xml
/usr/share/defaults/openzwave/config/dlink/dch-z120.xml
/usr/share/defaults/openzwave/config/dlink/dch-z510.xml
/usr/share/defaults/openzwave/config/dome/0002.xml
/usr/share/defaults/openzwave/config/dome/0083.xml
/usr/share/defaults/openzwave/config/dome/0085.xml
/usr/share/defaults/openzwave/config/dome/0086.xml
/usr/share/defaults/openzwave/config/dome/0087.xml
/usr/share/defaults/openzwave/config/dome/0088.xml
/usr/share/defaults/openzwave/config/dome/0101.xml
/usr/share/defaults/openzwave/config/dome/0201.xml
/usr/share/defaults/openzwave/config/domitech/zb22uk.xml
/usr/share/defaults/openzwave/config/domitech/ze27eu.xml
/usr/share/defaults/openzwave/config/domux/DX1CA-Z.xml
/usr/share/defaults/openzwave/config/domux/DX1CG-Z.xml
/usr/share/defaults/openzwave/config/domux/DX1DS-Z.xml
/usr/share/defaults/openzwave/config/domux/DX1HT-Z.xml
/usr/share/defaults/openzwave/config/domux/DX1MS-Z.xml
/usr/share/defaults/openzwave/config/domux/DX1SA-Z.xml
/usr/share/defaults/openzwave/config/domux/DX1WL-Z.xml
/usr/share/defaults/openzwave/config/domux/DX2SK-Z.xml
/usr/share/defaults/openzwave/config/dragontech/wd-100.xml
/usr/share/defaults/openzwave/config/duwi/05458.xml
/usr/share/defaults/openzwave/config/duwi/ZWES1000.xml
/usr/share/defaults/openzwave/config/duwi/ZWESJ300.xml
/usr/share/defaults/openzwave/config/duwi/zwfb.xml
/usr/share/defaults/openzwave/config/ecolink/doorwindow.xml
/usr/share/defaults/openzwave/config/ecolink/firefighter.xml
/usr/share/defaults/openzwave/config/ecolink/motion.xml
/usr/share/defaults/openzwave/config/ecolink/sensor.xml
/usr/share/defaults/openzwave/config/electronicsolutions/dbmz.xml
/usr/share/defaults/openzwave/config/enerwave/zw15rmplus.xml
/usr/share/defaults/openzwave/config/enerwave/zw15s.xml
/usr/share/defaults/openzwave/config/enerwave/zw20r.xml
/usr/share/defaults/openzwave/config/enerwave/zw20rm.xml
/usr/share/defaults/openzwave/config/enerwave/zw500d.xml
/usr/share/defaults/openzwave/config/enerwave/zwn-bpc.xml
/usr/share/defaults/openzwave/config/enerwave/zwn-sc7.xml
/usr/share/defaults/openzwave/config/enerwave/zwnrsm1plus.xml
/usr/share/defaults/openzwave/config/enerwave/zwnrsm2plus.xml
/usr/share/defaults/openzwave/config/eurotronic/eur_cometz.xml
/usr/share/defaults/openzwave/config/eurotronic/eur_stellaz.xml
/usr/share/defaults/openzwave/config/everspring/ad146.xml
/usr/share/defaults/openzwave/config/everspring/ad147.xml
/usr/share/defaults/openzwave/config/everspring/an145.xml
/usr/share/defaults/openzwave/config/everspring/an158.xml
/usr/share/defaults/openzwave/config/everspring/an179.xml
/usr/share/defaults/openzwave/config/everspring/an180.xml
/usr/share/defaults/openzwave/config/everspring/an181.xml
/usr/share/defaults/openzwave/config/everspring/hac01.xml
/usr/share/defaults/openzwave/config/everspring/hsp02.xml
/usr/share/defaults/openzwave/config/everspring/se812.xml
/usr/share/defaults/openzwave/config/everspring/sf812.xml
/usr/share/defaults/openzwave/config/everspring/sm103.xml
/usr/share/defaults/openzwave/config/everspring/sp103.xml
/usr/share/defaults/openzwave/config/everspring/sp814.xml
/usr/share/defaults/openzwave/config/everspring/sp816.xml
/usr/share/defaults/openzwave/config/everspring/st812.xml
/usr/share/defaults/openzwave/config/everspring/st814.xml
/usr/share/defaults/openzwave/config/everspring/st815.xml
/usr/share/defaults/openzwave/config/everspring/tse03.xml
/usr/share/defaults/openzwave/config/everspringct/hsm02.xml
/usr/share/defaults/openzwave/config/evolve/lrm-as.xml
/usr/share/defaults/openzwave/config/evolve/lsm-15.xml
/usr/share/defaults/openzwave/config/evolve/ltm-5.xml
/usr/share/defaults/openzwave/config/fakro/zwp10.xml
/usr/share/defaults/openzwave/config/fakro/zwrs.xml
/usr/share/defaults/openzwave/config/fakro/zws12.xml
/usr/share/defaults/openzwave/config/fakro/zws230.xml
/usr/share/defaults/openzwave/config/fibaro/fgbs001.xml
/usr/share/defaults/openzwave/config/fibaro/fgcd001.xml
/usr/share/defaults/openzwave/config/fibaro/fgd211.xml
/usr/share/defaults/openzwave/config/fibaro/fgd212.xml
/usr/share/defaults/openzwave/config/fibaro/fgdw2.xml
/usr/share/defaults/openzwave/config/fibaro/fgfs101.xml
/usr/share/defaults/openzwave/config/fibaro/fgfs101zw5.xml
/usr/share/defaults/openzwave/config/fibaro/fggc001.xml
/usr/share/defaults/openzwave/config/fibaro/fgk001.xml
/usr/share/defaults/openzwave/config/fibaro/fgk10x.xml
/usr/share/defaults/openzwave/config/fibaro/fgkf601.xml
/usr/share/defaults/openzwave/config/fibaro/fgms.xml
/usr/share/defaults/openzwave/config/fibaro/fgmszw5.xml
/usr/share/defaults/openzwave/config/fibaro/fgpb101.xml
/usr/share/defaults/openzwave/config/fibaro/fgr221.xml
/usr/share/defaults/openzwave/config/fibaro/fgrgbwm441.xml
/usr/share/defaults/openzwave/config/fibaro/fgrm222.xml
/usr/share/defaults/openzwave/config/fibaro/fgs211.xml
/usr/share/defaults/openzwave/config/fibaro/fgs212.xml
/usr/share/defaults/openzwave/config/fibaro/fgs213.xml
/usr/share/defaults/openzwave/config/fibaro/fgs221.xml
/usr/share/defaults/openzwave/config/fibaro/fgs222.xml
/usr/share/defaults/openzwave/config/fibaro/fgs223.xml
/usr/share/defaults/openzwave/config/fibaro/fgsd002.xml
/usr/share/defaults/openzwave/config/fibaro/fgss101.xml
/usr/share/defaults/openzwave/config/fibaro/fgt001.xml
/usr/share/defaults/openzwave/config/fibaro/fgwpe.xml
/usr/share/defaults/openzwave/config/fibaro/fgwpfzw5.xml
/usr/share/defaults/openzwave/config/firstalert/zcombo.xml
/usr/share/defaults/openzwave/config/forest/fs2z5232000002.xml
/usr/share/defaults/openzwave/config/fortrezz/fmi.xml
/usr/share/defaults/openzwave/config/fortrezz/mimo2plus.xml
/usr/share/defaults/openzwave/config/fortrezz/mimolite.xml
/usr/share/defaults/openzwave/config/fortrezz/ssa2.xml
/usr/share/defaults/openzwave/config/fortrezz/ssa3.xml
/usr/share/defaults/openzwave/config/fortrezz/wv01.xml
/usr/share/defaults/openzwave/config/fortrezz/wwa02.xml
/usr/share/defaults/openzwave/config/frostdale/fdn2nxx.xml
/usr/share/defaults/openzwave/config/ge/12719-plugin-switch.xml
/usr/share/defaults/openzwave/config/ge/12724-dimmer.xml
/usr/share/defaults/openzwave/config/ge/14282-plugin-switch.xml
/usr/share/defaults/openzwave/config/ge/14288-outlet.xml
/usr/share/defaults/openzwave/config/ge/14291-switch.xml
/usr/share/defaults/openzwave/config/ge/14292-toggle-switch.xml
/usr/share/defaults/openzwave/config/ge/14294-dimmer.xml
/usr/share/defaults/openzwave/config/ge/14295-dimmer-toggle.xml
/usr/share/defaults/openzwave/config/ge/26931-motion-switch.xml
/usr/share/defaults/openzwave/config/ge/26933-motion-dimmer.xml
/usr/share/defaults/openzwave/config/ge/dimmer.xml
/usr/share/defaults/openzwave/config/ge/dimmer_module.xml
/usr/share/defaults/openzwave/config/ge/hinge-pin.xml
/usr/share/defaults/openzwave/config/ge/receptacle.xml
/usr/share/defaults/openzwave/config/ge/relay.xml
/usr/share/defaults/openzwave/config/ge/ze26i.xml
/usr/share/defaults/openzwave/config/ge/zw4001-switch.xml
/usr/share/defaults/openzwave/config/ge/zw6302.xml
/usr/share/defaults/openzwave/config/gocontrol/GC-TBZ48L.xml
/usr/share/defaults/openzwave/config/gr/gr105.xml
/usr/share/defaults/openzwave/config/gr/gr105n.xml
/usr/share/defaults/openzwave/config/graber/brz1.xml
/usr/share/defaults/openzwave/config/graber/vcz1.xml
/usr/share/defaults/openzwave/config/greenwave/powernode1.xml
/usr/share/defaults/openzwave/config/greenwave/powernode6.xml
/usr/share/defaults/openzwave/config/hank/hkzw-dws01.xml
/usr/share/defaults/openzwave/config/hank/hkzw-fld01.xml
/usr/share/defaults/openzwave/config/hank/hkzw-ms01.xml
/usr/share/defaults/openzwave/config/hank/hkzw-ms02.xml
/usr/share/defaults/openzwave/config/hank/hkzw-rgb01.xml
/usr/share/defaults/openzwave/config/hank/hkzw-so01-smartplug.xml
/usr/share/defaults/openzwave/config/hank/hkzw-so03.xml
/usr/share/defaults/openzwave/config/hank/hkzw-so05-smartplug.xml
/usr/share/defaults/openzwave/config/hank/scenecontroller1.xml
/usr/share/defaults/openzwave/config/hank/scenecontroller4.xml
/usr/share/defaults/openzwave/config/heiman/HS1CA-Z.xml
/usr/share/defaults/openzwave/config/heiman/HS1CG-Z.xml
/usr/share/defaults/openzwave/config/heiman/HS1DS-Z.xml
/usr/share/defaults/openzwave/config/heiman/HS1HT-Z.xml
/usr/share/defaults/openzwave/config/heiman/HS1MS-Z.xml
/usr/share/defaults/openzwave/config/heiman/HS1SA-Z.xml
/usr/share/defaults/openzwave/config/heiman/HS1WL-Z.xml
/usr/share/defaults/openzwave/config/heiman/HS2SK-Z.xml
/usr/share/defaults/openzwave/config/homeseer/ezmotionplus.xml
/usr/share/defaults/openzwave/config/homeseer/hs-ms100plus.xml
/usr/share/defaults/openzwave/config/homeseer/hs-wd100plus.xml
/usr/share/defaults/openzwave/config/homeseer/hs-wd200plus.xml
/usr/share/defaults/openzwave/config/homeseer/hs-ws100plus.xml
/usr/share/defaults/openzwave/config/homeseer/hs-ws200plus.xml
/usr/share/defaults/openzwave/config/homeseer/hsm100.xml
/usr/share/defaults/openzwave/config/homeseer/hsm200.xml
/usr/share/defaults/openzwave/config/homeseer/ztroller.xml
/usr/share/defaults/openzwave/config/honeywell/lynx-touch-l5100.xml
/usr/share/defaults/openzwave/config/honeywell/th8320zw1000.xml
/usr/share/defaults/openzwave/config/horstmann/asrzw.xml
/usr/share/defaults/openzwave/config/horstmann/hrt4zw.xml
/usr/share/defaults/openzwave/config/horstmann/scsc17.xml
/usr/share/defaults/openzwave/config/horstmann/ses302.xml
/usr/share/defaults/openzwave/config/horstmann/ses303.xml
/usr/share/defaults/openzwave/config/horstmann/sir321.xml
/usr/share/defaults/openzwave/config/horstmann/srt321.xml
/usr/share/defaults/openzwave/config/horstmann/srt323.xml
/usr/share/defaults/openzwave/config/horstmann/ssr302.xml
/usr/share/defaults/openzwave/config/idlock/idlock101.xml
/usr/share/defaults/openzwave/config/ingersoll/dwzwave1.xml
/usr/share/defaults/openzwave/config/inovelli/nzw1201.xml
/usr/share/defaults/openzwave/config/inovelli/nzw30.xml
/usr/share/defaults/openzwave/config/inovelli/nzw31.xml
/usr/share/defaults/openzwave/config/inovelli/nzw36.xml
/usr/share/defaults/openzwave/config/inovelli/nzw37.xml
/usr/share/defaults/openzwave/config/inovelli/nzw39.xml
/usr/share/defaults/openzwave/config/inovelli/nzw96.xml
/usr/share/defaults/openzwave/config/inovelli/nzw97.xml
/usr/share/defaults/openzwave/config/inovelli/simple_module.xml
/usr/share/defaults/openzwave/config/intermatic/ca8900.xml
/usr/share/defaults/openzwave/config/iris/rangeextender.xml
/usr/share/defaults/openzwave/config/kaipule/im20.xml
/usr/share/defaults/openzwave/config/kaipule/ix32.xml
/usr/share/defaults/openzwave/config/kwikset/smartcode.xml
/usr/share/defaults/openzwave/config/leviton/dz15s.xml
/usr/share/defaults/openzwave/config/leviton/dz6hd.xml
/usr/share/defaults/openzwave/config/leviton/dzpd3.xml
/usr/share/defaults/openzwave/config/leviton/rzi10.xml
/usr/share/defaults/openzwave/config/leviton/vrcpg.xml
/usr/share/defaults/openzwave/config/leviton/vrf01.xml
/usr/share/defaults/openzwave/config/leviton/vri06.xml
/usr/share/defaults/openzwave/config/leviton/vri10.xml
/usr/share/defaults/openzwave/config/linear/GC-TBZ48.xml
/usr/share/defaults/openzwave/config/linear/LB60Z-1.xml
/usr/share/defaults/openzwave/config/linear/PD300Z-2.xml
/usr/share/defaults/openzwave/config/linear/WA00Z-1.xml
/usr/share/defaults/openzwave/config/linear/WA105DBZ-1.xml
/usr/share/defaults/openzwave/config/linear/WADWAZ-1.xml
/usr/share/defaults/openzwave/config/linear/WAPIRZ-1.xml
/usr/share/defaults/openzwave/config/linear/WD500Z-1.xml
/usr/share/defaults/openzwave/config/linear/WD500Z5-1.xml
/usr/share/defaults/openzwave/config/linear/WS15Z-1.xml
/usr/share/defaults/openzwave/config/linear/WT00Z-1.xml
/usr/share/defaults/openzwave/config/logicsoft/ZHC5002.xml
/usr/share/defaults/openzwave/config/logicsoft/ZHC5010.xml
/usr/share/defaults/openzwave/config/manufacturer_specific.xml
/usr/share/defaults/openzwave/config/manufacturer_specific.xsd
/usr/share/defaults/openzwave/config/mcohome/mh8fceu.xml
/usr/share/defaults/openzwave/config/mcohome/mh9co2.xml
/usr/share/defaults/openzwave/config/mcohome/mhp210.xml
/usr/share/defaults/openzwave/config/mcohome/mhs311.xml
/usr/share/defaults/openzwave/config/mcohome/mhs312.xml
/usr/share/defaults/openzwave/config/mcohome/mhs314.xml
/usr/share/defaults/openzwave/config/mcohome/mhs411.xml
/usr/share/defaults/openzwave/config/mcohome/mhs412.xml
/usr/share/defaults/openzwave/config/mcohome/mhs513.xml
/usr/share/defaults/openzwave/config/merten/507801.xml
/usr/share/defaults/openzwave/config/merten/50x5xx.xml
/usr/share/defaults/openzwave/config/nexia/db100z.xml
/usr/share/defaults/openzwave/config/nodon/asp3100SmartPlug.xml
/usr/share/defaults/openzwave/config/nodon/crc3100OctanRemote.xml
/usr/share/defaults/openzwave/config/nodon/crc360xSofremote.xml
/usr/share/defaults/openzwave/config/nodon/cws3101wallswitch.xml
/usr/share/defaults/openzwave/config/nodon/msp31xxMicroSmartPlug.xml
/usr/share/defaults/openzwave/config/northq/nq9021.xml
/usr/share/defaults/openzwave/config/northq/nq9121.xml
/usr/share/defaults/openzwave/config/northq/nq92021.xml
/usr/share/defaults/openzwave/config/oomi/ft100.xml
/usr/share/defaults/openzwave/config/oomi/ft111.xml
/usr/share/defaults/openzwave/config/options.xml
/usr/share/defaults/openzwave/config/options.xsd
/usr/share/defaults/openzwave/config/philio/pan03.xml
/usr/share/defaults/openzwave/config/philio/pan04.xml
/usr/share/defaults/openzwave/config/philio/pan06.xml
/usr/share/defaults/openzwave/config/philio/pan07.xml
/usr/share/defaults/openzwave/config/philio/pan08.xml
/usr/share/defaults/openzwave/config/philio/pan11.xml
/usr/share/defaults/openzwave/config/philio/pan16.xml
/usr/share/defaults/openzwave/config/philio/phpab01.xml
/usr/share/defaults/openzwave/config/philio/phpat02.xml
/usr/share/defaults/openzwave/config/philio/phpsg01.xml
/usr/share/defaults/openzwave/config/philio/pse02.xml
/usr/share/defaults/openzwave/config/philio/psm02.xml
/usr/share/defaults/openzwave/config/philio/psp05.xml
/usr/share/defaults/openzwave/config/philio/psr04.xml
/usr/share/defaults/openzwave/config/philio/pst02-1c.xml
/usr/share/defaults/openzwave/config/philio/pst02-b.xml
/usr/share/defaults/openzwave/config/philio/pst02.xml
/usr/share/defaults/openzwave/config/polycontrol/doorlock.xml
/usr/share/defaults/openzwave/config/polycontrol/doorlockv3.xml
/usr/share/defaults/openzwave/config/polycontrol/keypad.xml
/usr/share/defaults/openzwave/config/polycontrol/polylock.xml
/usr/share/defaults/openzwave/config/popp/004407.xml
/usr/share/defaults/openzwave/config/popp/009105.xml
/usr/share/defaults/openzwave/config/popp/009303.xml
/usr/share/defaults/openzwave/config/popp/009402.xml
/usr/share/defaults/openzwave/config/popp/012501.xml
/usr/share/defaults/openzwave/config/popp/123580.xml
/usr/share/defaults/openzwave/config/popp/123601.xml
/usr/share/defaults/openzwave/config/popp/123658.xml
/usr/share/defaults/openzwave/config/popp/700045.xml
/usr/share/defaults/openzwave/config/popp/700168.xml
/usr/share/defaults/openzwave/config/popp/smoke-detector.xml
/usr/share/defaults/openzwave/config/popp/solar-siren.xml
/usr/share/defaults/openzwave/config/popp/zweather.xml
/usr/share/defaults/openzwave/config/qees/reto-dimmer-plus.xml
/usr/share/defaults/openzwave/config/qees/reto-plugin-switch.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHAA2.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHADx.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHBA2.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHBDx.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHCA2.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHCDx.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHDA2.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHDDx.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHIA2.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHIDxS1.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHIDxS2.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHJA2.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHJD1.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHKDx.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHLAx.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHLDx.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHNDx.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHODx.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHSDx.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHTDx.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHTDxS3.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHUD1.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHVDx.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHWD1.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHXDx.xml
/usr/share/defaults/openzwave/config/qubino/ZMNHZDx.xml
/usr/share/defaults/openzwave/config/rcs/em52-zw.xml
/usr/share/defaults/openzwave/config/rcs/pm12-zw.xml
/usr/share/defaults/openzwave/config/rcs/therm0005.xml
/usr/share/defaults/openzwave/config/rcs/therm0007.xml
/usr/share/defaults/openzwave/config/rcs/therm0009.xml
/usr/share/defaults/openzwave/config/remotec/zfm-80.xml
/usr/share/defaults/openzwave/config/remotec/zrc-90.xml
/usr/share/defaults/openzwave/config/remotec/zts-110.xml
/usr/share/defaults/openzwave/config/remotec/zts-500.xml
/usr/share/defaults/openzwave/config/remotec/zurc.xml
/usr/share/defaults/openzwave/config/remotec/zxt-120.xml
/usr/share/defaults/openzwave/config/schlage/BE468.xml
/usr/share/defaults/openzwave/config/schlage/BE469.xml
/usr/share/defaults/openzwave/config/schlagelink/itemp.xml
/usr/share/defaults/openzwave/config/schlagelink/minikeypad.xml
/usr/share/defaults/openzwave/config/sensative/strips.xml
/usr/share/defaults/openzwave/config/sensative/stripscomfort.xml
/usr/share/defaults/openzwave/config/shenzen_neo/ls01ch.xml
/usr/share/defaults/openzwave/config/shenzen_neo/ls02ch.xml
/usr/share/defaults/openzwave/config/shenzen_neo/nas-ab01z.xml
/usr/share/defaults/openzwave/config/shenzen_neo/nas-ds01z.xml
/usr/share/defaults/openzwave/config/shenzen_neo/nas-pd01z.xml
/usr/share/defaults/openzwave/config/shenzen_neo/nas-rc01z.xml
/usr/share/defaults/openzwave/config/shenzen_neo/nas-wr01z.xml
/usr/share/defaults/openzwave/config/shenzen_neo/nas-ws02z.xml
/usr/share/defaults/openzwave/config/steinel/is140-2.xml
/usr/share/defaults/openzwave/config/steinel/rs-led-d2.xml
/usr/share/defaults/openzwave/config/steinel/xled-home-2.xml
/usr/share/defaults/openzwave/config/stelpro/stzw402.xml
/usr/share/defaults/openzwave/config/swiid/swiidinter.xml
/usr/share/defaults/openzwave/config/swiid/swiidplug.xml
/usr/share/defaults/openzwave/config/telldus/tzdw100.xml
/usr/share/defaults/openzwave/config/telldus/tzwp100.xml
/usr/share/defaults/openzwave/config/telldus/tzwp102.xml
/usr/share/defaults/openzwave/config/thermofloor/heatit021.xml
/usr/share/defaults/openzwave/config/thermofloor/heatit033.xml
/usr/share/defaults/openzwave/config/trane/TZEMT400AB32MAA.xml
/usr/share/defaults/openzwave/config/trane/TZEMT400BB32MAA.xml
/usr/share/defaults/openzwave/config/trane/TZEMT524AA21MA.xml
/usr/share/defaults/openzwave/config/tronika/zsc01d.xml
/usr/share/defaults/openzwave/config/vision/zd2102.xml
/usr/share/defaults/openzwave/config/vision/zd2105us5.xml
/usr/share/defaults/openzwave/config/vision/zd2201.xml
/usr/share/defaults/openzwave/config/vision/zd2301.xml
/usr/share/defaults/openzwave/config/vision/zf5201.xml
/usr/share/defaults/openzwave/config/vision/zg8101.xml
/usr/share/defaults/openzwave/config/vision/zl7261.xml
/usr/share/defaults/openzwave/config/vision/zl7431.xml
/usr/share/defaults/openzwave/config/vision/zm1601eu.xml
/usr/share/defaults/openzwave/config/vision/zm1601eu5.xml
/usr/share/defaults/openzwave/config/vision/zm1602eu.xml
/usr/share/defaults/openzwave/config/vision/zm1602eu5.xml
/usr/share/defaults/openzwave/config/vision/zp3102.xml
/usr/share/defaults/openzwave/config/vision/zp3111.xml
/usr/share/defaults/openzwave/config/vision/zs5101eu.xml
/usr/share/defaults/openzwave/config/vitrum/vitrumBS.xml
/usr/share/defaults/openzwave/config/waynedalton/WDTC-20.xml
/usr/share/defaults/openzwave/config/wenzhou/sm103.xml
/usr/share/defaults/openzwave/config/wenzhou/tsp01.xml
/usr/share/defaults/openzwave/config/wenzhou/tz55.xml
/usr/share/defaults/openzwave/config/wenzhou/tz56.xml
/usr/share/defaults/openzwave/config/wenzhou/tz65d.xml
/usr/share/defaults/openzwave/config/wenzhou/tz66d.xml
/usr/share/defaults/openzwave/config/wenzhou/tz67.xml
/usr/share/defaults/openzwave/config/wenzhou/tz68.xml
/usr/share/defaults/openzwave/config/wenzhou/tz69.xml
/usr/share/defaults/openzwave/config/wenzhou/tz74.xml
/usr/share/defaults/openzwave/config/wenzhou/tz79.xml
/usr/share/defaults/openzwave/config/wenzhou/tz88.xml
/usr/share/defaults/openzwave/config/widom/UBS104.xml
/usr/share/defaults/openzwave/config/widom/UME304C_S.xml
/usr/share/defaults/openzwave/config/widom/WDS.xml
/usr/share/defaults/openzwave/config/zipato/MiniKeypad.xml
/usr/share/defaults/openzwave/config/zipato/RGBBulb.xml
/usr/share/defaults/openzwave/config/zipato/RGBBulb2.xml
/usr/share/defaults/openzwave/config/zipato/pan04.xml
/usr/share/defaults/openzwave/config/zipato/vszd2102.xml
/usr/share/defaults/openzwave/config/zipato/zp3102.xml
/usr/share/defaults/openzwave/config/zooz/zen06.xml
/usr/share/defaults/openzwave/config/zooz/zen07.xml
/usr/share/defaults/openzwave/config/zooz/zen15.xml
/usr/share/defaults/openzwave/config/zooz/zen20.xml
/usr/share/defaults/openzwave/config/zooz/zen21.xml
/usr/share/defaults/openzwave/config/zooz/zen22.xml
/usr/share/defaults/openzwave/config/zooz/zen22v2.xml
/usr/share/defaults/openzwave/config/zooz/zen23.xml
/usr/share/defaults/openzwave/config/zooz/zen24.xml
/usr/share/defaults/openzwave/config/zooz/zse08.xml
/usr/share/defaults/openzwave/config/zooz/zse09.xml
/usr/share/defaults/openzwave/config/zooz/zse30.xml
/usr/share/defaults/openzwave/config/zooz/zse33.xml
/usr/share/defaults/openzwave/config/zooz/zse40.xml
/usr/share/defaults/openzwave/config/zwave.me/ZME_05431.xml
/usr/share/defaults/openzwave/config/zwave.me/ZME_05461.xml
/usr/share/defaults/openzwave/config/zwave.me/ZME_06433.xml
/usr/share/defaults/openzwave/config/zwave.me/ZME_06436.xml
/usr/share/defaults/openzwave/config/zwave.me/ZME_064381.xml
/usr/share/defaults/openzwave/config/zwave.me/ZME_064435.xml
/usr/share/defaults/openzwave/config/zwave.me/ZME_KFOB-S.xml
/usr/share/defaults/openzwave/config/zwave.me/ZME_RC2.xml
/usr/share/defaults/openzwave/config/zwave.me/ZME_WALLC-S.xml
/usr/share/defaults/openzwave/config/zwave.me/ZME_WCD2.xml
/usr/share/defaults/openzwave/config/zwave.me/ZUno.xml
/usr/share/defaults/openzwave/config/zwave.me/iTemp.xml
/usr/share/defaults/openzwave/config/zwave.me/kfob.xml
/usr/share/defaults/openzwave/config/zwave.me/popp_kfob-c.xml
/usr/share/defaults/openzwave/config/zwave.me/zweather.xml
/usr/share/defaults/openzwave/config/zwcfg.xsd
/usr/share/defaults/openzwave/config/zwp/WD-100.xml
/usr/share/defaults/openzwave/config/zwscene.xsd
/usr/share/defaults/openzwave/cooper/RF9501.xml
/usr/share/defaults/openzwave/cooper/RF9505-T.xml
/usr/share/defaults/openzwave/cooper/RF9517.xml
/usr/share/defaults/openzwave/cooper/RF9540-N.xml
/usr/share/defaults/openzwave/cooper/RF9542-Z.xml
/usr/share/defaults/openzwave/cooper/RFWC5.xml
/usr/share/defaults/openzwave/danfoss/living.xml
/usr/share/defaults/openzwave/danfoss/rsroom.xml
/usr/share/defaults/openzwave/danfoss/z.xml
/usr/share/defaults/openzwave/device_classes.xml
/usr/share/defaults/openzwave/device_classes.xsd
/usr/share/defaults/openzwave/device_configuration.xsd
/usr/share/defaults/openzwave/devolo/connectz.xml
/usr/share/defaults/openzwave/devolo/mt02648.xml
/usr/share/defaults/openzwave/devolo/mt02755.xml
/usr/share/defaults/openzwave/devolo/mt02758.xml
/usr/share/defaults/openzwave/devolo/mt02792.xml
/usr/share/defaults/openzwave/devolo/mt2646.xml
/usr/share/defaults/openzwave/devolo/mt2647.xml
/usr/share/defaults/openzwave/devolo/mt2651.xml
/usr/share/defaults/openzwave/devolo/mt2652.xml
/usr/share/defaults/openzwave/devolo/mt2653.xml
/usr/share/defaults/openzwave/devolo/mt2756.xml
/usr/share/defaults/openzwave/devolo/rs014G0159.xml
/usr/share/defaults/openzwave/dlink/dch-z110.xml
/usr/share/defaults/openzwave/dlink/dch-z120.xml
/usr/share/defaults/openzwave/dlink/dch-z510.xml
/usr/share/defaults/openzwave/dome/0002.xml
/usr/share/defaults/openzwave/dome/0083.xml
/usr/share/defaults/openzwave/dome/0085.xml
/usr/share/defaults/openzwave/dome/0086.xml
/usr/share/defaults/openzwave/dome/0087.xml
/usr/share/defaults/openzwave/dome/0088.xml
/usr/share/defaults/openzwave/dome/0101.xml
/usr/share/defaults/openzwave/dome/0201.xml
/usr/share/defaults/openzwave/domitech/zb22uk.xml
/usr/share/defaults/openzwave/domitech/ze27eu.xml
/usr/share/defaults/openzwave/domux/DX1CA-Z.xml
/usr/share/defaults/openzwave/domux/DX1CG-Z.xml
/usr/share/defaults/openzwave/domux/DX1DS-Z.xml
/usr/share/defaults/openzwave/domux/DX1HT-Z.xml
/usr/share/defaults/openzwave/domux/DX1MS-Z.xml
/usr/share/defaults/openzwave/domux/DX1SA-Z.xml
/usr/share/defaults/openzwave/domux/DX1WL-Z.xml
/usr/share/defaults/openzwave/domux/DX2SK-Z.xml
/usr/share/defaults/openzwave/dragontech/wd-100.xml
/usr/share/defaults/openzwave/duwi/05458.xml
/usr/share/defaults/openzwave/duwi/ZWES1000.xml
/usr/share/defaults/openzwave/duwi/ZWESJ300.xml
/usr/share/defaults/openzwave/duwi/zwfb.xml
/usr/share/defaults/openzwave/ecolink/doorwindow.xml
/usr/share/defaults/openzwave/ecolink/firefighter.xml
/usr/share/defaults/openzwave/ecolink/motion.xml
/usr/share/defaults/openzwave/ecolink/sensor.xml
/usr/share/defaults/openzwave/electronicsolutions/dbmz.xml
/usr/share/defaults/openzwave/enerwave/zw15rmplus.xml
/usr/share/defaults/openzwave/enerwave/zw15s.xml
/usr/share/defaults/openzwave/enerwave/zw20r.xml
/usr/share/defaults/openzwave/enerwave/zw20rm.xml
/usr/share/defaults/openzwave/enerwave/zw500d.xml
/usr/share/defaults/openzwave/enerwave/zwn-bpc.xml
/usr/share/defaults/openzwave/enerwave/zwn-sc7.xml
/usr/share/defaults/openzwave/enerwave/zwnrsm1plus.xml
/usr/share/defaults/openzwave/enerwave/zwnrsm2plus.xml
/usr/share/defaults/openzwave/eurotronic/eur_cometz.xml
/usr/share/defaults/openzwave/eurotronic/eur_stellaz.xml
/usr/share/defaults/openzwave/everspring/ad146.xml
/usr/share/defaults/openzwave/everspring/ad147.xml
/usr/share/defaults/openzwave/everspring/an145.xml
/usr/share/defaults/openzwave/everspring/an158.xml
/usr/share/defaults/openzwave/everspring/an179.xml
/usr/share/defaults/openzwave/everspring/an180.xml
/usr/share/defaults/openzwave/everspring/an181.xml
/usr/share/defaults/openzwave/everspring/hac01.xml
/usr/share/defaults/openzwave/everspring/hsp02.xml
/usr/share/defaults/openzwave/everspring/se812.xml
/usr/share/defaults/openzwave/everspring/sf812.xml
/usr/share/defaults/openzwave/everspring/sm103.xml
/usr/share/defaults/openzwave/everspring/sp103.xml
/usr/share/defaults/openzwave/everspring/sp814.xml
/usr/share/defaults/openzwave/everspring/sp815.xml
/usr/share/defaults/openzwave/everspring/sp816.xml
/usr/share/defaults/openzwave/everspring/st812.xml
/usr/share/defaults/openzwave/everspring/st814.xml
/usr/share/defaults/openzwave/everspring/st815.xml
/usr/share/defaults/openzwave/everspring/tse03.xml
/usr/share/defaults/openzwave/everspringct/hsm02.xml
/usr/share/defaults/openzwave/evolve/lrm-as.xml
/usr/share/defaults/openzwave/evolve/lsm-15.xml
/usr/share/defaults/openzwave/evolve/ltm-5.xml
/usr/share/defaults/openzwave/fakro/zwp10.xml
/usr/share/defaults/openzwave/fakro/zwrs.xml
/usr/share/defaults/openzwave/fakro/zws12.xml
/usr/share/defaults/openzwave/fakro/zws230.xml
/usr/share/defaults/openzwave/fibaro/fgbs001.xml
/usr/share/defaults/openzwave/fibaro/fgcd001.xml
/usr/share/defaults/openzwave/fibaro/fgd211.xml
/usr/share/defaults/openzwave/fibaro/fgd212.xml
/usr/share/defaults/openzwave/fibaro/fgdw2.xml
/usr/share/defaults/openzwave/fibaro/fgfs101.xml
/usr/share/defaults/openzwave/fibaro/fgfs101zw5.xml
/usr/share/defaults/openzwave/fibaro/fggc001.xml
/usr/share/defaults/openzwave/fibaro/fgk001.xml
/usr/share/defaults/openzwave/fibaro/fgk10x.xml
/usr/share/defaults/openzwave/fibaro/fgkf601.xml
/usr/share/defaults/openzwave/fibaro/fgms.xml
/usr/share/defaults/openzwave/fibaro/fgmszw5.xml
/usr/share/defaults/openzwave/fibaro/fgpb101.xml
/usr/share/defaults/openzwave/fibaro/fgr221.xml
/usr/share/defaults/openzwave/fibaro/fgrgbwm441.xml
/usr/share/defaults/openzwave/fibaro/fgrm222.xml
/usr/share/defaults/openzwave/fibaro/fgs211.xml
/usr/share/defaults/openzwave/fibaro/fgs212.xml
/usr/share/defaults/openzwave/fibaro/fgs213.xml
/usr/share/defaults/openzwave/fibaro/fgs221.xml
/usr/share/defaults/openzwave/fibaro/fgs222.xml
/usr/share/defaults/openzwave/fibaro/fgs223.xml
/usr/share/defaults/openzwave/fibaro/fgsd002.xml
/usr/share/defaults/openzwave/fibaro/fgss101.xml
/usr/share/defaults/openzwave/fibaro/fgt001.xml
/usr/share/defaults/openzwave/fibaro/fgwpe.xml
/usr/share/defaults/openzwave/fibaro/fgwpfzw5.xml
/usr/share/defaults/openzwave/fibaro/fgwpg111.xml
/usr/share/defaults/openzwave/firstalert/zcombo.xml
/usr/share/defaults/openzwave/forest/fs2z5232000002.xml
/usr/share/defaults/openzwave/fortrezz/fmi.xml
/usr/share/defaults/openzwave/fortrezz/mimo2plus.xml
/usr/share/defaults/openzwave/fortrezz/mimolite.xml
/usr/share/defaults/openzwave/fortrezz/ssa2.xml
/usr/share/defaults/openzwave/fortrezz/ssa3.xml
/usr/share/defaults/openzwave/fortrezz/wv01.xml
/usr/share/defaults/openzwave/fortrezz/wwa02.xml
/usr/share/defaults/openzwave/frostdale/fdn2nxx.xml
/usr/share/defaults/openzwave/ge/12719-plugin-switch.xml
/usr/share/defaults/openzwave/ge/12724-dimmer.xml
/usr/share/defaults/openzwave/ge/14282-plugin-switch.xml
/usr/share/defaults/openzwave/ge/14288-outlet.xml
/usr/share/defaults/openzwave/ge/14291-switch.xml
/usr/share/defaults/openzwave/ge/14292-toggle-switch.xml
/usr/share/defaults/openzwave/ge/14294-dimmer.xml
/usr/share/defaults/openzwave/ge/14295-dimmer-toggle.xml
/usr/share/defaults/openzwave/ge/26931-motion-switch.xml
/usr/share/defaults/openzwave/ge/26933-motion-dimmer.xml
/usr/share/defaults/openzwave/ge/28167-plugin-dimmer.xml
/usr/share/defaults/openzwave/ge/dimmer.xml
/usr/share/defaults/openzwave/ge/dimmer_module.xml
/usr/share/defaults/openzwave/ge/hinge-pin.xml
/usr/share/defaults/openzwave/ge/receptacle.xml
/usr/share/defaults/openzwave/ge/relay.xml
/usr/share/defaults/openzwave/ge/ze26i.xml
/usr/share/defaults/openzwave/ge/zw4001-switch.xml
/usr/share/defaults/openzwave/ge/zw6302.xml
/usr/share/defaults/openzwave/gocontrol/GC-TBZ48L.xml
/usr/share/defaults/openzwave/gr/gr105.xml
/usr/share/defaults/openzwave/gr/gr105n.xml
/usr/share/defaults/openzwave/graber/brz1.xml
/usr/share/defaults/openzwave/graber/vcz1.xml
/usr/share/defaults/openzwave/greenwave/powernode1.xml
/usr/share/defaults/openzwave/greenwave/powernode6.xml
/usr/share/defaults/openzwave/hank/hkzw-dws01.xml
/usr/share/defaults/openzwave/hank/hkzw-fld01.xml
/usr/share/defaults/openzwave/hank/hkzw-ms01.xml
/usr/share/defaults/openzwave/hank/hkzw-ms02.xml
/usr/share/defaults/openzwave/hank/hkzw-rgb01.xml
/usr/share/defaults/openzwave/hank/hkzw-so01-smartplug.xml
/usr/share/defaults/openzwave/hank/hkzw-so03.xml
/usr/share/defaults/openzwave/hank/hkzw-so05-smartplug.xml
/usr/share/defaults/openzwave/hank/scenecontroller1.xml
/usr/share/defaults/openzwave/hank/scenecontroller4.xml
/usr/share/defaults/openzwave/heiman/HS1CA-Z.xml
/usr/share/defaults/openzwave/heiman/HS1CG-Z.xml
/usr/share/defaults/openzwave/heiman/HS1DS-Z.xml
/usr/share/defaults/openzwave/heiman/HS1HT-Z.xml
/usr/share/defaults/openzwave/heiman/HS1MS-Z.xml
/usr/share/defaults/openzwave/heiman/HS1SA-Z.xml
/usr/share/defaults/openzwave/heiman/HS1WL-Z.xml
/usr/share/defaults/openzwave/heiman/HS2SK-Z.xml
/usr/share/defaults/openzwave/homeseer/ezmotionplus.xml
/usr/share/defaults/openzwave/homeseer/hs-fls100plus.xml
/usr/share/defaults/openzwave/homeseer/hs-ls100plus.xml
/usr/share/defaults/openzwave/homeseer/hs-ms100plus.xml
/usr/share/defaults/openzwave/homeseer/hs-wd100plus.xml
/usr/share/defaults/openzwave/homeseer/hs-wd200plus.xml
/usr/share/defaults/openzwave/homeseer/hs-ws100plus.xml
/usr/share/defaults/openzwave/homeseer/hs-ws200plus.xml
/usr/share/defaults/openzwave/homeseer/hsm100.xml
/usr/share/defaults/openzwave/homeseer/hsm200.xml
/usr/share/defaults/openzwave/homeseer/ztroller.xml
/usr/share/defaults/openzwave/honeywell/39351-ZW3005.xml
/usr/share/defaults/openzwave/honeywell/lynx-touch-l5100.xml
/usr/share/defaults/openzwave/honeywell/th8320zw1000.xml
/usr/share/defaults/openzwave/horstmann/asrzw.xml
/usr/share/defaults/openzwave/horstmann/hrt4zw.xml
/usr/share/defaults/openzwave/horstmann/scsc17.xml
/usr/share/defaults/openzwave/horstmann/ses302.xml
/usr/share/defaults/openzwave/horstmann/ses303.xml
/usr/share/defaults/openzwave/horstmann/sir321.xml
/usr/share/defaults/openzwave/horstmann/srt321.xml
/usr/share/defaults/openzwave/horstmann/srt323.xml
/usr/share/defaults/openzwave/horstmann/ssr302.xml
/usr/share/defaults/openzwave/horstmann/ssr303.xml
/usr/share/defaults/openzwave/idlock/idlock101.xml
/usr/share/defaults/openzwave/ingersoll/dwzwave1.xml
/usr/share/defaults/openzwave/inovelli/nzw1201.xml
/usr/share/defaults/openzwave/inovelli/nzw30.xml
/usr/share/defaults/openzwave/inovelli/nzw31.xml
/usr/share/defaults/openzwave/inovelli/nzw36.xml
/usr/share/defaults/openzwave/inovelli/nzw37.xml
/usr/share/defaults/openzwave/inovelli/nzw39.xml
/usr/share/defaults/openzwave/inovelli/nzw96.xml
/usr/share/defaults/openzwave/inovelli/nzw97.xml
/usr/share/defaults/openzwave/inovelli/simple_module.xml
/usr/share/defaults/openzwave/intermatic/ca8900.xml
/usr/share/defaults/openzwave/iris/rangeextender.xml
/usr/share/defaults/openzwave/kaipule/im20.xml
/usr/share/defaults/openzwave/kaipule/ix32.xml
/usr/share/defaults/openzwave/kwikset/smartcode.xml
/usr/share/defaults/openzwave/leviton/dz15s.xml
/usr/share/defaults/openzwave/leviton/dz6hd.xml
/usr/share/defaults/openzwave/leviton/dzpd3.xml
/usr/share/defaults/openzwave/leviton/rzi10.xml
/usr/share/defaults/openzwave/leviton/vrcpg.xml
/usr/share/defaults/openzwave/leviton/vre06.xml
/usr/share/defaults/openzwave/leviton/vrf01.xml
/usr/share/defaults/openzwave/leviton/vri06.xml
/usr/share/defaults/openzwave/leviton/vri10.xml
/usr/share/defaults/openzwave/linear/GC-TBZ48.xml
/usr/share/defaults/openzwave/linear/LB60Z-1.xml
/usr/share/defaults/openzwave/linear/PD300Z-2.xml
/usr/share/defaults/openzwave/linear/WA00Z-1.xml
/usr/share/defaults/openzwave/linear/WA105DBZ-1.xml
/usr/share/defaults/openzwave/linear/WADWAZ-1.xml
/usr/share/defaults/openzwave/linear/WAPIRZ-1.xml
/usr/share/defaults/openzwave/linear/WD500Z-1.xml
/usr/share/defaults/openzwave/linear/WD500Z5-1.xml
/usr/share/defaults/openzwave/linear/WS15Z-1.xml
/usr/share/defaults/openzwave/linear/WT00Z-1.xml
/usr/share/defaults/openzwave/logicsoft/ZHC5002.xml
/usr/share/defaults/openzwave/logicsoft/ZHC5010.xml
/usr/share/defaults/openzwave/manufacturer_specific.xml
/usr/share/defaults/openzwave/manufacturer_specific.xsd
/usr/share/defaults/openzwave/mcohome/a8-9.xml
/usr/share/defaults/openzwave/mcohome/mh8fceu.xml
/usr/share/defaults/openzwave/mcohome/mh9co2.xml
/usr/share/defaults/openzwave/mcohome/mhp210.xml
/usr/share/defaults/openzwave/mcohome/mhs311.xml
/usr/share/defaults/openzwave/mcohome/mhs312.xml
/usr/share/defaults/openzwave/mcohome/mhs314.xml
/usr/share/defaults/openzwave/mcohome/mhs411.xml
/usr/share/defaults/openzwave/mcohome/mhs412.xml
/usr/share/defaults/openzwave/mcohome/mhs513.xml
/usr/share/defaults/openzwave/merten/507801.xml
/usr/share/defaults/openzwave/merten/50x5xx.xml
/usr/share/defaults/openzwave/nexia/db100z.xml
/usr/share/defaults/openzwave/nodon/asp3100SmartPlug.xml
/usr/share/defaults/openzwave/nodon/crc3100OctanRemote.xml
/usr/share/defaults/openzwave/nodon/crc360xSofremote.xml
/usr/share/defaults/openzwave/nodon/cws3101wallswitch.xml
/usr/share/defaults/openzwave/nodon/msp31xxMicroSmartPlug.xml
/usr/share/defaults/openzwave/northq/nq9021.xml
/usr/share/defaults/openzwave/northq/nq9121.xml
/usr/share/defaults/openzwave/northq/nq92021.xml
/usr/share/defaults/openzwave/oomi/ft100.xml
/usr/share/defaults/openzwave/oomi/ft111.xml
/usr/share/defaults/openzwave/options.xml
/usr/share/defaults/openzwave/options.xsd
/usr/share/defaults/openzwave/philio/pad02.xml
/usr/share/defaults/openzwave/philio/pan03.xml
/usr/share/defaults/openzwave/philio/pan04.xml
/usr/share/defaults/openzwave/philio/pan06.xml
/usr/share/defaults/openzwave/philio/pan07.xml
/usr/share/defaults/openzwave/philio/pan08.xml
/usr/share/defaults/openzwave/philio/pan11.xml
/usr/share/defaults/openzwave/philio/pan16.xml
/usr/share/defaults/openzwave/philio/phpab01.xml
/usr/share/defaults/openzwave/philio/phpat02.xml
/usr/share/defaults/openzwave/philio/phpsg01.xml
/usr/share/defaults/openzwave/philio/pse02.xml
/usr/share/defaults/openzwave/philio/psm02.xml
/usr/share/defaults/openzwave/philio/psp05.xml
/usr/share/defaults/openzwave/philio/psr04.xml
/usr/share/defaults/openzwave/philio/pst02-1c.xml
/usr/share/defaults/openzwave/philio/pst02-b.xml
/usr/share/defaults/openzwave/philio/pst02.xml
/usr/share/defaults/openzwave/polycontrol/doorlock.xml
/usr/share/defaults/openzwave/polycontrol/doorlockv3.xml
/usr/share/defaults/openzwave/polycontrol/keypad.xml
/usr/share/defaults/openzwave/polycontrol/polylock.xml
/usr/share/defaults/openzwave/popp/004407.xml
/usr/share/defaults/openzwave/popp/009105.xml
/usr/share/defaults/openzwave/popp/009303.xml
/usr/share/defaults/openzwave/popp/009402.xml
/usr/share/defaults/openzwave/popp/009501.xml
/usr/share/defaults/openzwave/popp/012501.xml
/usr/share/defaults/openzwave/popp/123580.xml
/usr/share/defaults/openzwave/popp/123601.xml
/usr/share/defaults/openzwave/popp/123658.xml
/usr/share/defaults/openzwave/popp/700045.xml
/usr/share/defaults/openzwave/popp/700168.xml
/usr/share/defaults/openzwave/popp/smoke-detector.xml
/usr/share/defaults/openzwave/popp/solar-siren.xml
/usr/share/defaults/openzwave/popp/zweather.xml
/usr/share/defaults/openzwave/pyozw_config.version
/usr/share/defaults/openzwave/qees/reto-dimmer-plus.xml
/usr/share/defaults/openzwave/qees/reto-plugin-switch.xml
/usr/share/defaults/openzwave/qubino/ZMNHAA2.xml
/usr/share/defaults/openzwave/qubino/ZMNHADx.xml
/usr/share/defaults/openzwave/qubino/ZMNHBA2.xml
/usr/share/defaults/openzwave/qubino/ZMNHBDx.xml
/usr/share/defaults/openzwave/qubino/ZMNHCA2.xml
/usr/share/defaults/openzwave/qubino/ZMNHCDx.xml
/usr/share/defaults/openzwave/qubino/ZMNHDA2.xml
/usr/share/defaults/openzwave/qubino/ZMNHDDx.xml
/usr/share/defaults/openzwave/qubino/ZMNHIA2.xml
/usr/share/defaults/openzwave/qubino/ZMNHIDxS1.xml
/usr/share/defaults/openzwave/qubino/ZMNHIDxS2.xml
/usr/share/defaults/openzwave/qubino/ZMNHJA2.xml
/usr/share/defaults/openzwave/qubino/ZMNHJD1.xml
/usr/share/defaults/openzwave/qubino/ZMNHKDx.xml
/usr/share/defaults/openzwave/qubino/ZMNHLAx.xml
/usr/share/defaults/openzwave/qubino/ZMNHLDx.xml
/usr/share/defaults/openzwave/qubino/ZMNHNDx.xml
/usr/share/defaults/openzwave/qubino/ZMNHODx.xml
/usr/share/defaults/openzwave/qubino/ZMNHSDx.xml
/usr/share/defaults/openzwave/qubino/ZMNHTDx.xml
/usr/share/defaults/openzwave/qubino/ZMNHTDxS3.xml
/usr/share/defaults/openzwave/qubino/ZMNHUD1.xml
/usr/share/defaults/openzwave/qubino/ZMNHVDx.xml
/usr/share/defaults/openzwave/qubino/ZMNHWD1.xml
/usr/share/defaults/openzwave/qubino/ZMNHXDx.xml
/usr/share/defaults/openzwave/qubino/ZMNHYDx.xml
/usr/share/defaults/openzwave/qubino/ZMNHZDx.xml
/usr/share/defaults/openzwave/rcs/em52-zw.xml
/usr/share/defaults/openzwave/rcs/pm12-zw.xml
/usr/share/defaults/openzwave/rcs/therm0005.xml
/usr/share/defaults/openzwave/rcs/therm0007.xml
/usr/share/defaults/openzwave/rcs/therm0009.xml
/usr/share/defaults/openzwave/remotec/zfm-80.xml
/usr/share/defaults/openzwave/remotec/zrc-90.xml
/usr/share/defaults/openzwave/remotec/zts-110.xml
/usr/share/defaults/openzwave/remotec/zts-500.xml
/usr/share/defaults/openzwave/remotec/zurc.xml
/usr/share/defaults/openzwave/remotec/zxt-120.xml
/usr/share/defaults/openzwave/remotec/zxt-600.xml
/usr/share/defaults/openzwave/schlage/BE468.xml
/usr/share/defaults/openzwave/schlage/BE469.xml
/usr/share/defaults/openzwave/schlagelink/itemp.xml
/usr/share/defaults/openzwave/schlagelink/minikeypad.xml
/usr/share/defaults/openzwave/sensative/strips.xml
/usr/share/defaults/openzwave/sensative/stripscomfort.xml
/usr/share/defaults/openzwave/shenzen_neo/ls01ch.xml
/usr/share/defaults/openzwave/shenzen_neo/ls02ch.xml
/usr/share/defaults/openzwave/shenzen_neo/nas-ab01z.xml
/usr/share/defaults/openzwave/shenzen_neo/nas-ds01z.xml
/usr/share/defaults/openzwave/shenzen_neo/nas-pd01z.xml
/usr/share/defaults/openzwave/shenzen_neo/nas-rc01z.xml
/usr/share/defaults/openzwave/shenzen_neo/nas-wr01z.xml
/usr/share/defaults/openzwave/shenzen_neo/nas-ws02z.xml
/usr/share/defaults/openzwave/steinel/is140-2.xml
/usr/share/defaults/openzwave/steinel/l810-led-ihf.xml
/usr/share/defaults/openzwave/steinel/rs-led-d2.xml
/usr/share/defaults/openzwave/steinel/xled-home-2.xml
/usr/share/defaults/openzwave/stelpro/stzw402.xml
/usr/share/defaults/openzwave/swiid/swiidinter.xml
/usr/share/defaults/openzwave/swiid/swiidplug.xml
/usr/share/defaults/openzwave/telldus/tzdw100.xml
/usr/share/defaults/openzwave/telldus/tzwp100.xml
/usr/share/defaults/openzwave/telldus/tzwp102.xml
/usr/share/defaults/openzwave/thermofloor/heatit021.xml
/usr/share/defaults/openzwave/thermofloor/heatit033.xml
/usr/share/defaults/openzwave/trane/TZEMT400AB32MAA.xml
/usr/share/defaults/openzwave/trane/TZEMT400BB32MAA.xml
/usr/share/defaults/openzwave/trane/TZEMT524AA21MA.xml
/usr/share/defaults/openzwave/tronika/zsc01d.xml
/usr/share/defaults/openzwave/vision/zd2102.xml
/usr/share/defaults/openzwave/vision/zd2105us5.xml
/usr/share/defaults/openzwave/vision/zd2201.xml
/usr/share/defaults/openzwave/vision/zd2301.xml
/usr/share/defaults/openzwave/vision/zf5201.xml
/usr/share/defaults/openzwave/vision/zg8101.xml
/usr/share/defaults/openzwave/vision/zl7261.xml
/usr/share/defaults/openzwave/vision/zl7431.xml
/usr/share/defaults/openzwave/vision/zm1601eu.xml
/usr/share/defaults/openzwave/vision/zm1601eu5.xml
/usr/share/defaults/openzwave/vision/zm1602eu.xml
/usr/share/defaults/openzwave/vision/zm1602eu5.xml
/usr/share/defaults/openzwave/vision/zp3102.xml
/usr/share/defaults/openzwave/vision/zp3111.xml
/usr/share/defaults/openzwave/vision/zs5101eu.xml
/usr/share/defaults/openzwave/vitrum/vitrumBS.xml
/usr/share/defaults/openzwave/waynedalton/WDTC-20.xml
/usr/share/defaults/openzwave/wenzhou/sm103.xml
/usr/share/defaults/openzwave/wenzhou/tsp01.xml
/usr/share/defaults/openzwave/wenzhou/tz55.xml
/usr/share/defaults/openzwave/wenzhou/tz56.xml
/usr/share/defaults/openzwave/wenzhou/tz57.xml
/usr/share/defaults/openzwave/wenzhou/tz65d.xml
/usr/share/defaults/openzwave/wenzhou/tz66d.xml
/usr/share/defaults/openzwave/wenzhou/tz67.xml
/usr/share/defaults/openzwave/wenzhou/tz68.xml
/usr/share/defaults/openzwave/wenzhou/tz69.xml
/usr/share/defaults/openzwave/wenzhou/tz74.xml
/usr/share/defaults/openzwave/wenzhou/tz79.xml
/usr/share/defaults/openzwave/wenzhou/tz88.xml
/usr/share/defaults/openzwave/widom/UBS104.xml
/usr/share/defaults/openzwave/widom/UME304C_S.xml
/usr/share/defaults/openzwave/widom/WDS.xml
/usr/share/defaults/openzwave/zipato/MiniKeypad.xml
/usr/share/defaults/openzwave/zipato/RGBBulb.xml
/usr/share/defaults/openzwave/zipato/RGBBulb2.xml
/usr/share/defaults/openzwave/zipato/pan04.xml
/usr/share/defaults/openzwave/zipato/vszd2102.xml
/usr/share/defaults/openzwave/zipato/zp3102.xml
/usr/share/defaults/openzwave/zooz/zen06.xml
/usr/share/defaults/openzwave/zooz/zen07.xml
/usr/share/defaults/openzwave/zooz/zen15.xml
/usr/share/defaults/openzwave/zooz/zen20.xml
/usr/share/defaults/openzwave/zooz/zen21.xml
/usr/share/defaults/openzwave/zooz/zen22.xml
/usr/share/defaults/openzwave/zooz/zen22v2.xml
/usr/share/defaults/openzwave/zooz/zen23.xml
/usr/share/defaults/openzwave/zooz/zen24.xml
/usr/share/defaults/openzwave/zooz/zse08.xml
/usr/share/defaults/openzwave/zooz/zse09.xml
/usr/share/defaults/openzwave/zooz/zse18.xml
/usr/share/defaults/openzwave/zooz/zse30.xml
/usr/share/defaults/openzwave/zooz/zse33.xml
/usr/share/defaults/openzwave/zooz/zse40.xml
/usr/share/defaults/openzwave/zwave.me/ZME_05431.xml
/usr/share/defaults/openzwave/zwave.me/ZME_05461.xml
/usr/share/defaults/openzwave/zwave.me/ZME_06433.xml
/usr/share/defaults/openzwave/zwave.me/ZME_06436.xml
/usr/share/defaults/openzwave/zwave.me/ZME_064381.xml
/usr/share/defaults/openzwave/zwave.me/ZME_064435.xml
/usr/share/defaults/openzwave/zwave.me/ZME_KFOB-S.xml
/usr/share/defaults/openzwave/zwave.me/ZME_RC2.xml
/usr/share/defaults/openzwave/zwave.me/ZME_WALLC-S.xml
/usr/share/defaults/openzwave/zwave.me/ZME_WCD2.xml
/usr/share/defaults/openzwave/zwave.me/ZUno.xml
/usr/share/defaults/openzwave/zwave.me/iTemp.xml
/usr/share/defaults/openzwave/zwave.me/kfob.xml
/usr/share/defaults/openzwave/zwave.me/popp_kfob-c.xml
/usr/share/defaults/openzwave/zwave.me/zweather.xml
/usr/share/defaults/openzwave/zwcfg.xsd
/usr/share/defaults/openzwave/zwp/WD-100.xml
/usr/share/defaults/openzwave/zwscene.xsd

%files dev
%defattr(-,root,root,-)
/usr/include/openzwave/Bitfield.h
/usr/include/openzwave/Defs.h
/usr/include/openzwave/DoxygenMain.h
/usr/include/openzwave/Driver.h
/usr/include/openzwave/Group.h
/usr/include/openzwave/Manager.h
/usr/include/openzwave/Msg.h
/usr/include/openzwave/Node.h
/usr/include/openzwave/Notification.h
/usr/include/openzwave/OZWException.h
/usr/include/openzwave/Options.h
/usr/include/openzwave/Scene.h
/usr/include/openzwave/Utils.h
/usr/include/openzwave/ZWSecurity.h
/usr/include/openzwave/aes/aes.h
/usr/include/openzwave/aes/aescpp.h
/usr/include/openzwave/aes/aesopt.h
/usr/include/openzwave/aes/aestab.h
/usr/include/openzwave/aes/brg_endian.h
/usr/include/openzwave/aes/brg_types.h
/usr/include/openzwave/command_classes/Alarm.h
/usr/include/openzwave/command_classes/ApplicationStatus.h
/usr/include/openzwave/command_classes/Association.h
/usr/include/openzwave/command_classes/AssociationCommandConfiguration.h
/usr/include/openzwave/command_classes/Basic.h
/usr/include/openzwave/command_classes/BasicWindowCovering.h
/usr/include/openzwave/command_classes/Battery.h
/usr/include/openzwave/command_classes/CRC16Encap.h
/usr/include/openzwave/command_classes/CentralScene.h
/usr/include/openzwave/command_classes/ClimateControlSchedule.h
/usr/include/openzwave/command_classes/Clock.h
/usr/include/openzwave/command_classes/Color.h
/usr/include/openzwave/command_classes/CommandClass.h
/usr/include/openzwave/command_classes/CommandClasses.h
/usr/include/openzwave/command_classes/Configuration.h
/usr/include/openzwave/command_classes/ControllerReplication.h
/usr/include/openzwave/command_classes/DeviceResetLocally.h
/usr/include/openzwave/command_classes/DoorLock.h
/usr/include/openzwave/command_classes/DoorLockLogging.h
/usr/include/openzwave/command_classes/EnergyProduction.h
/usr/include/openzwave/command_classes/Hail.h
/usr/include/openzwave/command_classes/Indicator.h
/usr/include/openzwave/command_classes/Language.h
/usr/include/openzwave/command_classes/Lock.h
/usr/include/openzwave/command_classes/ManufacturerSpecific.h
/usr/include/openzwave/command_classes/Meter.h
/usr/include/openzwave/command_classes/MeterPulse.h
/usr/include/openzwave/command_classes/MultiChannelAssociation.h
/usr/include/openzwave/command_classes/MultiCmd.h
/usr/include/openzwave/command_classes/MultiInstance.h
/usr/include/openzwave/command_classes/NoOperation.h
/usr/include/openzwave/command_classes/NodeNaming.h
/usr/include/openzwave/command_classes/Powerlevel.h
/usr/include/openzwave/command_classes/Proprietary.h
/usr/include/openzwave/command_classes/Protection.h
/usr/include/openzwave/command_classes/SceneActivation.h
/usr/include/openzwave/command_classes/Security.h
/usr/include/openzwave/command_classes/SensorAlarm.h
/usr/include/openzwave/command_classes/SensorBinary.h
/usr/include/openzwave/command_classes/SensorMultilevel.h
/usr/include/openzwave/command_classes/SwitchAll.h
/usr/include/openzwave/command_classes/SwitchBinary.h
/usr/include/openzwave/command_classes/SwitchMultilevel.h
/usr/include/openzwave/command_classes/SwitchToggleBinary.h
/usr/include/openzwave/command_classes/SwitchToggleMultilevel.h
/usr/include/openzwave/command_classes/ThermostatFanMode.h
/usr/include/openzwave/command_classes/ThermostatFanState.h
/usr/include/openzwave/command_classes/ThermostatMode.h
/usr/include/openzwave/command_classes/ThermostatOperatingState.h
/usr/include/openzwave/command_classes/ThermostatSetpoint.h
/usr/include/openzwave/command_classes/TimeParameters.h
/usr/include/openzwave/command_classes/UserCode.h
/usr/include/openzwave/command_classes/Version.h
/usr/include/openzwave/command_classes/WakeUp.h
/usr/include/openzwave/command_classes/ZWavePlusInfo.h
/usr/include/openzwave/platform/Controller.h
/usr/include/openzwave/platform/Event.h
/usr/include/openzwave/platform/FileOps.h
/usr/include/openzwave/platform/HidController.h
/usr/include/openzwave/platform/Log.h
/usr/include/openzwave/platform/Mutex.h
/usr/include/openzwave/platform/Ref.h
/usr/include/openzwave/platform/SerialController.h
/usr/include/openzwave/platform/Stream.h
/usr/include/openzwave/platform/Thread.h
/usr/include/openzwave/platform/TimeStamp.h
/usr/include/openzwave/platform/Wait.h
/usr/include/openzwave/platform/unix/EventImpl.h
/usr/include/openzwave/platform/unix/FileOpsImpl.h
/usr/include/openzwave/platform/unix/LogImpl.h
/usr/include/openzwave/platform/unix/MutexImpl.h
/usr/include/openzwave/platform/unix/SerialControllerImpl.h
/usr/include/openzwave/platform/unix/ThreadImpl.h
/usr/include/openzwave/platform/unix/TimeStampImpl.h
/usr/include/openzwave/platform/unix/WaitImpl.h
/usr/include/openzwave/value_classes/Value.h
/usr/include/openzwave/value_classes/ValueBool.h
/usr/include/openzwave/value_classes/ValueButton.h
/usr/include/openzwave/value_classes/ValueByte.h
/usr/include/openzwave/value_classes/ValueDecimal.h
/usr/include/openzwave/value_classes/ValueID.h
/usr/include/openzwave/value_classes/ValueInt.h
/usr/include/openzwave/value_classes/ValueList.h
/usr/include/openzwave/value_classes/ValueRaw.h
/usr/include/openzwave/value_classes/ValueSchedule.h
/usr/include/openzwave/value_classes/ValueShort.h
/usr/include/openzwave/value_classes/ValueStore.h
/usr/include/openzwave/value_classes/ValueString.h
/usr/lib64/libopenzwave.so
/usr/lib64/pkgconfig/libopenzwave.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/openzwave-1.4.0/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libopenzwave.so.1.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libopenzwave/cpp_hidapi_LICENSE-bsd.txt
/usr/share/package-licenses/libopenzwave/cpp_hidapi_LICENSE-gpl3.txt
/usr/share/package-licenses/libopenzwave/cpp_hidapi_LICENSE-orig.txt
/usr/share/package-licenses/libopenzwave/cpp_hidapi_LICENSE.txt
/usr/share/package-licenses/libopenzwave/debian_copyright
/usr/share/package-licenses/libopenzwave/license_gpl.txt
/usr/share/package-licenses/libopenzwave/license_license.txt
